### ISSUE TITLE
Breakpoints get disable when debuggin with PDM Vault Browser

### ISSUE THREAD

**Issue by carlitoscarrara** [codestack-net-dev/pdm-vault-browser#1]
Hi,

I am trying to use this utility to debug a PDM Addin.

The problem is that when I set to start with PdmVaultBrowser.exe the breakpoint of my addin gets disable showing the error of the image:

![image](https://user-images.githubusercontent.com/8020816/48559416-63c9af80-e8ca-11e8-8fc3-c8ea555d1cbb.png)

Any idea of how can I solved this? I have already google and tried all the results, but I had no luck.

Regards,
Carlos

**Comment by carlitoscarrara** [comment]
Error message:

![image](https://user-images.githubusercontent.com/8020816/48559755-fa966c00-e8ca-11e8-8135-a471b3672084.png)

**Comment by codestackdev** [comment]
Did you downloaded this from the releases or compiled from your end, is it targeting Framework 4.0? 

"Source code is provided below (must be compiled in .NET Framework 4.0 otherwise the debug symbols will not be loaded):"

Reference: https://www.codestack.net/solidworks-pdm-api/getting-started/add-ins/debugging-best-practices/

I can reproduce this behaviour if I compile for anything other than FW 4.0.

**Comment by carlitoscarrara** [comment]
Hi, 
I have tried with the .exe on the release and with the .exe compiled on my end, and I'm getting the same behaviour.

My **addin** (.dll) target is .Net Framework 4.6.1

Is there any other information I can send to you?

Thanks,
Carlos

**Comment by codestackdev** [comment]
Hi,

Couple of more questions. Do you have pdb files generated? Can you try debugging via Notepad, does it work?

Thanks,
Artem

**Comment by carlitoscarrara** [comment]
Hi Artem,

I do have the .pdb files. By default they are not loaded, but I went to Debug -> Window -> Modules and load them.

I can debug correctly with notepad, sublimetext or any other similar exe.

I was making my own PDM vault browser utility, before I found yours; and I ran into the same problem. My breakpoints get disabled.

Regards,
Carlos

**Comment by carlitoscarrara** [comment]
Hi Artem,

Do you have any idea of what can be caussing this?

Best,
Carlos

**Comment by codestackdev** [comment]
Hi Carlos,

Sorry for late reply. Are you using PDM 2018 or 2019? Just thinking it might be something related to the target framework. From my tests I had exactly the same experience when I build this tool targeting Framework 4.5 or later (it only worked for 4.0), but that was for PDM 2017. Just thinking for newer version SW might updated their framework. Could you please try to compile this tool targeting FW 4.5, 4.6, 4.7 to see if it makes any difference?

Thanks,
Artem

**Comment by carlitoscarrara** [comment]
Hi Artem,

I could solved it adding an empty Form that stay behind the OpenDialog.

With this form the breakpoints start working correctly.

I don't actually understand why, but it works. Haha

Thanks
Regards,
Carlos

**Comment by codestackdev** [comment]
Hi Carlos,

Thanks a lot for sharing the workaround. Much appreciated.

Regards,
Artem
